778 Update conditional start event on parent change
camunda/camunda-bpmn-moddle pull request #77
Opened 2021-09-06 12:34 UTC by smbea

Related to https://github.com/bpmn-io/bpmn-js/issues/778

2021-09-06 14:04 UTC, pinussilvestrus reviewed
I like the descriptive implementation and test cases, it was easy to understand what's going on - good job 👍  Some things to consider codewise (cf. comments).

I saw that the commit message (cf. https://github.com/camunda/camunda-bpmn-moddle/pull/77/commits/4a2b45a9e28a32ee2b6c7e50734b5618e0706d4d) is quite extensive - maybe due to some refactorings & updates.

Let's keep it clean 

```sh
fix(moddle): remove variableEvents when StartEvent parent changes 

Related to bpmn-io/bpmn-js#778
```

2021-09-06 14:04 UTC, pinussilvestrus commented on lib/RemoveVariableEventBehaviour.js
> +          if (is(oldParent, 'bpmn:SubProcess') && !is(newParent, 'bpmn:SubProcess') && oldParentBusinessObject.get('triggeredByEvent')) {
The order of the conditions could be confusing (oldParent, newParent, oldParent...). Maybe we can do something like

```js
 if (
  is(oldParent, 'bpmn:SubProcess') && 
  oldParentBusinessObject.get('triggeredByEvent') && 
  !is(newParent, 'bpmn:SubProcess')
) { 
  ... 
}
 ```

2021-09-07 07:16 UTC, smbea commented
Changes overview:

@barmac I updated the way the objects were being modified, as we had talked about (using `bpmnFactory` and `moddleCopy` to create and modify a copy of each object)

@pinussilvestrus I fixed the consistency discrepancies and updated the test diagram to include more than one `eventDefinition` in the conditional `startEvent`

2021-09-07 07:52 UTC, barmac requested changes
I've left a couple of comments. Overall, the solution is heading into right direction, but some additional work needs to be done.

2021-09-07 07:52 UTC, barmac commented on lib/RemoveVariableEventBehaviour.js
> +    modeling.updateProperties(shape, { 'eventDefinitions': definitionsCopy });
We want to update event definitions only when it's necessary. As it is here in the code, the `eventDefinitions` property will be updated whenever one moves any shape as there are no conditions applied.

2021-09-07 07:52 UTC, barmac commented on lib/RemoveVariableEventBehaviour.js
> +        newDef.$parent = def.$parent;
We make a copy for each event definition which seems to be unnecessary when `camunda:variableEvents` is not found. Also, there are more types of event definitions, e.g. `bpmn:TimerEventDefinition`. We don't want to look into them or replace them.

2021-09-07 07:52 UTC, barmac commented on lib/RemoveVariableEventBehaviour.js
> +            is(oldParent, 'bpmn:SubProcess') &&
If a user already has a broken diagram, i.e. where a process child has `camunda:variableEvents`, we want to fix that. Thus, there is no need for the old parent check.

2021-09-07 07:52 UTC, barmac commented on lib/RemoveVariableEventBehaviour.js
> +  this.postExecuted(['shape.move'], function(context) {
We should also react to `shape.create` to fix the issue where possible.

2021-09-07 07:52 UTC, barmac commented on lib/RemoveVariableEventBehaviour.js
> +    modeling.updateProperties(shape, { 'eventDefinitions': definitionsCopy });
Also, let's not update the properties if no `camunda:variableEvents` had to be replaced.

2021-09-07 07:52 UTC, barmac commented on lib/RemoveVariableEventBehaviour.js
> +          ) {
This condition is checked multiple times while it could be checked once and earlier in the function.

2021-09-07 07:52 UTC, barmac commented on lib/RemoveVariableEventBehaviour.js
> +    // if shape is a startEvent
```suggestion
```
Duplicate of the code.

2021-09-07 07:52 UTC, barmac commented on lib/RemoveVariableEventBehaviour.js
> +          // if shape within an event subpprocess changes parent
We want to also fix the incorrect state. It's not necessary for the shape to change a parent. If it has `camunda:variableEvents` and it's incorrect, we should remove the property.

2021-09-08 09:47 UTC, smbea commented
Changes summary:
- The conditions for the property removal were changed according to the comments made
- Copy of eventDefinitions object and parent check is now only done once
- Flag was added to check if there was a need to update the eventDefinitions, instead of always updating
- Missing test case was added

2021-09-09 07:41 UTC, barmac approved these changes

2021-09-09 07:42 UTC, barmac commented
I've renamed a couple of variables, changed formatting, and squashed the commits. Ready to merge :)

2021-09-09 07:42 UTC, merged